services:
  api:
    image: emilpopovic/linkconvert:latest
    secrets:
      - spotify-client-id
      - spotify-client-secret
      - youtube-api-key
    environment:
      - API_URL=https://linkconvert.emilpopovic.me
      - SPOTIFY_TOKEN_FILE=/run/secrets/spotify-client-id
      - SPOTIFY_CLIENT_ID_FILE=/run/secrets/spotify-client-id
      - YOUTUBE_API_KEY_FILE=/run/secrets/youtube-api-key
    depends_on:
      - redis

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  spotify-client-id:
    external: true
  spotify-client-secret:
    external: true
  youtube-api-key:
    external: true
