
services:
  api:
    container_name: linkconvert-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - linkconvert
      - proxy-network

  redis:
    container_name: linkconvert-redis
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - linkconvert

networks:
  linkconvert:
  proxy-network:
    external: true
